package ir.ramtung.tinyme.domain.entity;

public enum MatchingOutcome {
    EXECUTED,
    NOT_ENOUGH_CREDIT,
    NOT_ENOUGH_POSITIONS,
    NOT_ENOUGH_QUANTITIES_TRADED,
    NOT_ABLE_TO_CREATE_STOP_LIMIT_ORDER,
    STOP_LIMIT_ORDER_ACCEPTED,
    STOP_LIMIT_ORDER_ACTIVATED
}
